name: pipeline-main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: 💻 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: 🚀 serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy --stage prd
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
          AWS_ENDPOINT_ARN: ${{ secrets.AWS_ENDPOINT_ARN }}
          ALEXA_SKILL_ID: ${{ secrets.ALEXA_SKILL_ID }}
          ALEXA_VENDOR_ID: ${{ secrets.ALEXA_VENDOR_ID }}
          ALEXA_CLIENT_SECRET: ${{ secrets.ALEXA_CLIENT_SECRET }}
          ALEXA_CLIENT_ID: ${{ secrets.ALEXA_CLIENT_ID }}
